# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fe72526622f6637bf9efeeae45d9cb5bcb6dd45d4504b7d555f91317108e0341603cc1369b09a9bdeae5c92bd6c2e9fb4fe202769a7965fa41191941264f06e

test:
  secret_key_base: b116a5317c803de8ad9ce6bd1c85d9b7b99f6917af0af0600b891f1ed0fb492ca80bb39bb5851fae9a4187799df9fe74b53e54c270f956ef82df4eb795d7af89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
